name: nvchecker

on:
  schedule:
  - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  nvchecker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install nvchecker
      run: |
        sudo apt-get update
        sudo apt-get install nvchecker
    - name: Run nvchecker
      run: |
        nvchecker -c nvchecker.toml | tee nvchecker.out
        test -s nvchecker.out && exit 1
